import { EonetEvent } from '@/types';

// MOCK DATA — Fallback hydration layer when the FastAPI backend is offline.
// 5 events spanning all hazard categories with realistic asset data.

export const MOCK_EVENTS: EonetEvent[] = [
  {
    id: 'EONET-7102',
    title: 'Wildfire — Northern California Sector 4',
    category: 'Wildfires',
    severity: 'CRITICAL',
    threat_score: 8.7,
    latitude: 39.7596,
    longitude: -121.6219,
    timestamp: '2026-07-31T06:42:00Z',
    radius_km: 25,
    exposed_assets: [
      {
        id: 'A-101',
        name: 'Paradise Substation Alpha',
        type: 'Power',
        distance_km: 1.2,
        risk_level: 'HIGH',
        lat: 39.768,
        lng: -121.609,
      },
      {
        id: 'A-102',
        name: 'Feather River Memorial Hospital',
        type: 'Health',
        distance_km: 3.8,
        risk_level: 'CRITICAL',
        lat: 39.752,
        lng: -121.637,
      },
      {
        id: 'A-103',
        name: 'State Route 70 Corridor',
        type: 'Transport',
        distance_km: 0.5,
        risk_level: 'HIGH',
        lat: 39.755,
        lng: -121.628,
      },
      {
        id: 'A-104',
        name: 'Oroville Wastewater Facility',
        type: 'Utility',
        distance_km: 6.1,
        risk_level: 'MEDIUM',
        lat: 39.73,
        lng: -121.6,
      },
    ],
    summary:
      'Active crown fire spreading eastward at approximately 18 km/h driven by Diablo wind conditions. Primary transmission grid at Paradise Substation Alpha faces direct ember-cast threat. Feather River Memorial Hospital has initiated evacuation protocols. Firefighting aircraft deployed along SR-70 firebreak.',
  },
  {
    id: 'EONET-7099',
    title: 'Severe Tropical Cyclone — Bay of Bengal',
    category: 'Severe Storms',
    severity: 'HIGH',
    threat_score: 7.2,
    latitude: 16.432,
    longitude: 88.125,
    timestamp: '2026-07-31T03:15:00Z',
    radius_km: 80,
    exposed_assets: [
      {
        id: 'A-201',
        name: 'Paradip Port Authority Terminal',
        type: 'Transport',
        distance_km: 18.0,
        risk_level: 'HIGH',
        lat: 20.316,
        lng: 86.608,
      },
      {
        id: 'A-202',
        name: 'Paradeep Fertiliser Plant Grid',
        type: 'Power',
        distance_km: 22.4,
        risk_level: 'HIGH',
        lat: 20.28,
        lng: 86.63,
      },
      {
        id: 'A-203',
        name: 'Bhubaneswar Medical College',
        type: 'Health',
        distance_km: 54.0,
        risk_level: 'MEDIUM',
        lat: 20.296,
        lng: 85.824,
      },
    ],
    summary:
      'Category 3 cyclone (sustained winds 185 km/h) tracking NNW toward Odisha coastline. Storm surge forecast of 3.5–5 m threatens Paradip Port operations and low-lying industrial infrastructure. Coastal evacuation corridors along NH-53 are under assessment.',
  },
  {
    id: 'EONET-7088',
    title: 'Volcanic Activity — Kilauea East Rift Zone',
    category: 'Volcanoes',
    severity: 'HIGH',
    threat_score: 6.8,
    latitude: 19.4069,
    longitude: -155.2834,
    timestamp: '2026-07-30T21:00:00Z',
    radius_km: 15,
    exposed_assets: [
      {
        id: 'A-301',
        name: 'Hilo International Airport',
        type: 'Transport',
        distance_km: 28.5,
        risk_level: 'MEDIUM',
        lat: 19.721,
        lng: -155.048,
      },
      {
        id: 'A-302',
        name: 'Puna Geothermal Venture Plant',
        type: 'Power',
        distance_km: 4.9,
        risk_level: 'CRITICAL',
        lat: 19.479,
        lng: -154.909,
      },
      {
        id: 'A-303',
        name: 'Pahoa Community Hospital',
        type: 'Health',
        distance_km: 9.3,
        risk_level: 'HIGH',
        lat: 19.498,
        lng: -154.944,
      },
    ],
    summary:
      'New eruptive fissure opened on lower East Rift Zone emitting lava flows at 150 m³/s. Sulfur dioxide emission rates at 2,800 tonnes/day triggering vog advisory across Puna district. Puna Geothermal Venture Plant under immediate lava-flow threat; hydrogen sulfide venting risk elevated.',
  },
  {
    id: 'EONET-7095',
    title: 'Flash Flooding — Greater Houston Metro',
    category: 'Floods',
    severity: 'MEDIUM',
    threat_score: 5.4,
    latitude: 29.7604,
    longitude: -95.3698,
    timestamp: '2026-07-31T01:30:00Z',
    radius_km: 40,
    exposed_assets: [
      {
        id: 'A-401',
        name: 'Texas Medical Center Complex',
        type: 'Health',
        distance_km: 5.2,
        risk_level: 'HIGH',
        lat: 29.706,
        lng: -95.398,
      },
      {
        id: 'A-402',
        name: 'George Bush Intercontinental Airport',
        type: 'Transport',
        distance_km: 32.1,
        risk_level: 'MEDIUM',
        lat: 29.99,
        lng: -95.336,
      },
      {
        id: 'A-403',
        name: 'CenterPoint Energy Substation W7',
        type: 'Power',
        distance_km: 8.7,
        risk_level: 'MEDIUM',
        lat: 29.742,
        lng: -95.461,
      },
      {
        id: 'A-404',
        name: 'Houston Water Treatment Plant Almeda',
        type: 'Utility',
        distance_km: 11.0,
        risk_level: 'HIGH',
        lat: 29.691,
        lng: -95.367,
      },
    ],
    summary:
      'Stalled frontal boundary producing rainfall totals of 280mm in 6 hours across Harris County. Buffalo Bayou levels at 43 ft, exceeding 2017 Harvey benchmark at gauge stations. Texas Medical Center has activated flood protocols; basement infrastructure at risk.',
  },
  {
    id: 'EONET-7078',
    title: 'Dust Storm — Phoenix Metropolitan Area',
    category: 'Dust and Haze',
    severity: 'LOW',
    threat_score: 3.1,
    latitude: 33.4484,
    longitude: -112.074,
    timestamp: '2026-07-30T18:45:00Z',
    radius_km: 60,
    exposed_assets: [
      {
        id: 'A-501',
        name: 'Phoenix Sky Harbor International Airport',
        type: 'Transport',
        distance_km: 4.3,
        risk_level: 'MEDIUM',
        lat: 33.437,
        lng: -112.008,
      },
      {
        id: 'A-502',
        name: 'APS Palo Verde Nuclear Generating Station',
        type: 'Power',
        distance_km: 55.2,
        risk_level: 'LOW',
        lat: 33.389,
        lng: -112.862,
      },
    ],
    summary:
      'Haboob (dust wall) measuring 1,800m in height advancing at 65 km/h from Maricopa. Visibility reduced to <100m along I-10. Phoenix Sky Harbor has suspended runway operations. Particulate PM10 concentrations exceeding 800 µg/m³ across metro grid.',
  },
];